name       : python-pyusb
version    : 1.0.2
release    : 4
source     :
    - https://github.com/pyusb/pyusb/archive/v1.0.2.tar.gz : 49dfa601f28e9399df62004170cfb623197ad32d8399885b7f789775767b50c3
license    : Apache-2.0
component  : programming.python
summary    : USB access on python
description: |
    The PyUSB module provides for Python easy access to the host machine's Universal Serial Bus (USB) system.
builddeps  :
    - pkgconfig(libusb-1.0)
    - pkgconfig(python3)
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
