name       : python-pyusb
version    : 1.0.0
release    : 1
source     :
    - https://github.com/walac/pyusb/archive/1.0.0.tar.gz : 52106ce23ccc3b804335952aa48f7d5ce94f7ec27b44bb2d523eac92b97ace63
license    : BSD-3-Clause
component  : programming.python
summary    : USB access on python
description: |
    The PyUSB module provides for Python easy access to the host machine's Universal Serial Bus (USB) system.
builddeps  :
    - pkgconfig(libusb-1.0)
    - pkgconfig(python-3.5)
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
