name       : python-pyusb
version    : 1.2.1
release    : 8
source     :
    - https://github.com/pyusb/pyusb/releases/download/v1.2.1/pyusb-1.2.1.tar.gz : a4cc7404a203144754164b8b40994e2849fde1cfff06b08492f12fff9d9de7b9
homepage   : https://pyusb.github.io/pyusb/
license    : Apache-2.0
component  : programming.python
summary    : USB access on python
description: |
    The PyUSB module provides for Python easy access to the host machine's Universal Serial Bus (USB) system.
builddeps  :
    - pkgconfig(libusb-1.0)
    - pkgconfig(python3)
    - python-setuptools-scm
build      : |
    %python3_setup
install    : |
    %python3_install
