name       : python-pyusb
version    : 1.1.0
release    : 5
source     :
    - https://github.com/pyusb/pyusb/releases/download/v1.1.0/pyusb-1.1.0.tar.gz : d69ed64bff0e2102da11b3f49567256867853b861178689671a163d30865c298
homepage   : https://pyusb.github.io/pyusb/
license    : Apache-2.0
component  : programming.python
summary    : USB access on python
description: |
    The PyUSB module provides for Python easy access to the host machine's Universal Serial Bus (USB) system.
builddeps  :
    - pkgconfig(libusb-1.0)
    - pkgconfig(python3)
    - python-setuptools-scm
build      : |
    %python3_setup
install    : |
    %python3_install
