name       : python-pyusb
version    : 1.1.1
release    : 6
source     :
    - https://github.com/pyusb/pyusb/releases/download/v1.1.1/pyusb-1.1.1.tar.gz : 7d449ad916ce58aff60b89aae0b65ac130f289c24d6a5b7b317742eccffafc38
homepage   : https://pyusb.github.io/pyusb/
license    : Apache-2.0
component  : programming.python
summary    : USB access on python
description: |
    The PyUSB module provides for Python easy access to the host machine's Universal Serial Bus (USB) system.
builddeps  :
    - pkgconfig(libusb-1.0)
    - pkgconfig(python3)
    - python-setuptools-scm
build      : |
    %python3_setup
install    : |
    %python3_install
